In [1]:
import pandas as pd

__1. Opening a local Csv file__

In [2]:
train = pd.read_csv('C:\\Users\\Malik Gee\\Desktop\\Gathering_Data\\Datasets\\aug_train.csv')

__2. Opening a Csv file from an Url__

In [3]:
import requests
from io import StringIO

url = 'https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv'

headers = {'User-Agent':'Mozilla/5.0 (Macintosh: Intel Mac os x 10.14; rv:66.0) Gecko/20100101 Firefox/66.0'}
req = requests.get(url,headers=headers)
data = StringIO(req.text)

df = pd.read_csv(data)

__3. Sep Parameter__

In [4]:
df1 = pd.read_csv('C:\\Users\\Malik Gee\\Desktop\\Gathering_Data\\Datasets\\movie_metadata.tsv',sep='\t')

Adding names for columns

In [5]:
columns = [
    "Wikipedia_movie_ID",
    "Freebase_movie_ID",
    "Movie_name",
    "Movie_release_date",
    "Movie_box_office_revenue",
    "Movie_runtime",
    "Movie_languages",
    "Movie_countries",
    "Movie_genres",
]
df1 = pd.read_csv('C:\\Users\\Malik Gee\\Desktop\\Gathering_Data\\Datasets\\movie_metadata.tsv',sep='\t',names=columns)

__4. Index_col Parameter__

In [6]:
train1 = pd.read_csv('C:\\Users\\Malik Gee\\Desktop\\Gathering_Data\\Datasets\\aug_train.csv',index_col='enrollee_id')

__5. Header Parameter__

__6. use_cols Parameter__

In [7]:
pd.read_csv('C:\\Users\\Malik Gee\\Desktop\\Gathering_Data\\Datasets\\aug_train.csv',usecols=['enrollee_id','gender','education_level','major_discipline'])

       enrollee_id gender education_level major_discipline
0             8949   Male        Graduate             STEM
1            29725   Male        Graduate             STEM
2            11561    NaN        Graduate             STEM
3            33241    NaN        Graduate  Business Degree
4              666   Male         Masters             STEM
...            ...    ...             ...              ...
19153         7386   Male        Graduate       Humanities
19154        31398   Male        Graduate             STEM
19155        24576   Male        Graduate             STEM
19156         5756   Male     High School              NaN
19157        23834    NaN  Primary School              NaN

[19158 rows x 4 columns]

__7. squeeze Parameter__

__8. skiprows/nrows Parameter__

__9. encoding Parameter__

In [8]:
pd.read_csv('C:\\Users\\Malik Gee\\Desktop\\Gathering_Data\\Datasets\\aug_train.csv',encoding='latin-1').head(5)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

__10. skip bad lines Parameter__

error_bad_lines = False

__11. dtype Parameter__

__12. handling Dates Parameter__

__13. converters Parameter__

In [9]:
def rename(name):
    if name == 'Royal Challengers Bangalore':
        return 'RCB'
    else:
        return name
    



pd.read_csv('C:\\Users\\Malik Gee\\Desktop\\Gathering_Data\\Datasets\\ipl-matches.csv',converters={'Team1':rename,'Team2':rename}).head(5)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,RCB,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,RCB,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

__14. na_values Parameter__

            Export Dataset

In [12]:
ipl = pd.read_csv('C:\\Users\\Malik Gee\\Desktop\\Gathering_Data\\Datasets\\ipl-matches.csv')

In [22]:
temp = ipl.groupby('Venue')['Season'].count().reset_index()
temp.to_csv('Matches_per_venue.csv')