In [2]:
import pandas as pd

Excel File

In [3]:
pd.read_excel('C:\\Users\\Malik Gee\\Desktop\\Gathering_Data\\Datasets2\\Orders.xlsx')

     OrderID  CustomerID  EmployeeID  OrderDate  ShipperID
0      10248          90           5 1996-07-04          3
1      10249          81           6 1996-07-05          1
2      10250          34           4 1996-07-08          2
3      10251          84           3 1996-07-08          1
4      10252          76           4 1996-07-09          2
..       ...         ...         ...        ...        ...
191    10439          51           6 1997-02-07          3
192    10440          71           4 1997-02-10          2
193    10441          55           3 1997-02-10          2
194    10442          20           3 1997-02-11          2
195    10443          66           8 1997-02-12          1

[196 rows x 5 columns]

text file

In [5]:
pd.read_csv('C:\\Users\\Malik Gee\\Desktop\\Gathering_Data\\Datasets2\\sample3.txt',sep='\t')

                         Quod equidem non reprehendo;
0   Lorem ipsum dolor sit amet, consectetur adipis...
1   Iam id ipsum absurdum, maximum malum neglegi. ...
2                           Quis istum dolorem timet?
3   Summus dolor plures dies manere non potest? Di...
4   Ex eorum enim scriptis et institutis cum omnis...
5   Quod si ita est, sequitur id ipsum, quod te ve...
6   Quem si tenueris, non modo meum Ciceronem, sed...
7   Stulti autem malorum memoria torquentur, sapie...
8   Esse enim quam vellet iniquus iustus poterat i...
9   Quae autem natura suae primae institutionis ob...
10  Verum tamen cum de rebus grandioribus dicas, i...
11  Hoc est non modo cor non habere, sed ne palatu...
12  Voluptatem cum summum bonum diceret, primum in...
13                              Idemne, quod iucunde?
14  Haec mihi videtur delicatior, ut ita dicam, mo...

            export to excel

In [7]:
pd.read_csv('C:\\Users\\Malik Gee\\Desktop\\Gathering_Data\\Matches_per_venue.csv',index_col='Unnamed: 0').to_excel('venues.xlsx')