In [1]:
import pandas as pd
import requests

In [2]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=1a4ead1fcfed9f5b2459d45bc702fa67')

In [3]:
pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

,id,title,overview,release_date,popularity,vote_average,vote_count
0,980431,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",2026-07-24,143.3652,9.273,821
1,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,25.0413,8.900,347
2,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,59.0684,8.886,2096
3,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,58.1371,8.727,31005
4,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,The Demon Slayer Corps are drawn into the Infi...,2025-07-18,126.2866,8.699,1799
5,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,53.7827,8.686,23328
6,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,92.8659,8.684,3979
7,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,138.5220,8.700,6980
8,1232449,Young Hearts,14-year-old Elias increasingly feels like an o...,2024-10-26,18.9445,8.563,303
9,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,34.6694,8.571,14167
10,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,35.6237,8.570,17728
11,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,29.4893,8.567,10226
12,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,64.9427,8.534,36365
13,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,36.0107,8.534,18675
14,1218925,Chainsaw Man - The Movie: Reze Arc,"In a brutal war between devils, hunters, and s...",2025-09-19,37.9413,8.500,1102
15,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,16.0038,8.506,4611
16,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,37.8131,8.506,19592
17,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-17,53.3217,8.503,27063
18,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,39.8677,8.490,21070
19,157336,Interstellar,The adventures of a group of explorers who mak...,2014-11-05,70.6117,8.484,40714

In [6]:
dfs = []

for i in range(1,556):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=1a4ead1fcfed9f5b2459d45bc702fa67&page={}'.format(i))
    
    data = response.json()
    if 'results' in data and data['results']:
      
      temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
      dfs.append(temp_df)

df = pd.concat(dfs,ignore_index=True)

In [7]:
df.to_csv('movies.csv')

In [11]:
df = pd.read_csv('C:\\Users\\Malik Gee\\Desktop\\Gathering_Data\\movies.csv')
df.drop('Unnamed: 0', axis=1)

,id,title,overview,release_date,popularity,vote_average,vote_count
0,980431,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",2026-07-24,143.3652,9.273,821
1,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,25.0413,8.900,347
2,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,59.0684,8.886,2096
3,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,58.1371,8.727,31005
4,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,The Demon Slayer Corps are drawn into the Infi...,2025-07-18,126.2866,8.699,1799
...,...,...,...,...,...,...,...
9995,7839,Wedding Daze,"After losing the woman of his dreams, Anderson...",2006-09-09,4.6927,5.636,418
9996,1083433,I Know What You Did Last Summer,When five friends inadvertently cause a deadly...,2025-07-16,10.2836,5.600,840
9997,434555,The Possession of Hannah Grace,When a cop who is just out of rehab takes the ...,2018-11-29,6.3171,5.635,1505
9998,13260,Semi-Pro,"Jackie Moon is the owner, promoter, coach, and...",2008-02-28,3.8926,5.635,899
9999,7341,The Rage: Carrie 2,A horrible massacre strikes up after an outcas...,1999-03-12,4.3238,5.634,474

In [10]:
df

,Unnamed: 0,id,title,overview,release_date,popularity,vote_average,vote_count
0,0,980431,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",2026-07-24,143.3652,9.273,821
1,1,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,25.0413,8.900,347
2,2,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,59.0684,8.886,2096
3,3,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,58.1371,8.727,31005
4,4,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,The Demon Slayer Corps are drawn into the Infi...,2025-07-18,126.2866,8.699,1799
...,...,...,...,...,...,...,...,...
9995,9995,7839,Wedding Daze,"After losing the woman of his dreams, Anderson...",2006-09-09,4.6927,5.636,418
9996,9996,1083433,I Know What You Did Last Summer,When five friends inadvertently cause a deadly...,2025-07-16,10.2836,5.600,840
9997,9997,434555,The Possession of Hannah Grace,When a cop who is just out of rehab takes the ...,2018-11-29,6.3171,5.635,1505
9998,9998,13260,Semi-Pro,"Jackie Moon is the owner, promoter, coach, and...",2008-02-28,3.8926,5.635,899
9999,9999,7341,The Rage: Carrie 2,A horrible massacre strikes up after an outcas...,1999-03-12,4.3238,5.634,474